### ISSUE TITLE
Fixing duplicate character

### ISSUE THREAD

**Issue by rsfriedman** [foundations-software-engineering/clue-less-board-game#21]
Need to fix the case where you select a character that already exists--should have an error.

**Comment by JerroldJV** [comment]
This only occurs if there are duplicate character objects- which shouldn't happen in a production system.

**Comment by JerroldJV** [comment]
Oh, and that would be the case if I had implement isCharacterInGame.... which I will do right now :)

**Comment by GregHilston** [comment]
Can this now be closed per the merged status?
